name: flutter_sixvalley_ecommerce
description: A new Flutter setup application for starting a project.

publish_to: 'none'

version: 2.0.9+9

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  animations: ^2.0.8
  cached_network_image: ^3.2.3
  card_swiper: ^3.0.1
  connectivity: ^3.0.3
  country_code_picker: ^3.0.0
  country_currency_pickers: ^2.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0-prev2
  dotted_border: ^2.0.0+3
  dotted_line: ^3.2.2
  dropdown_search: ^5.0.3
  emoji_picker_flutter: ^1.6.2
  expandable_bottom_sheet: ^1.1.1+1
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.6
  flutter:
    sdk: flutter
  flutter_downloader: ^1.8.0+1
  flutter_facebook_auth: ^4.4.1+1
  flutter_google_places: ^0.3.0
  flutter_html: ^3.0.0-alpha.3
  flutter_html_table: ^3.0.0-alpha.3
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_rating_bar: ^4.0.0
  flutter_slidable: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^1.0.3
  flutter_typeahead: ^4.0.0
  flutter_widget_from_html: ^0.8.5
  flutter_widget_from_html_core: ^0.8.5+3
  fluttertoast: ^8.0.9
  geocoding: ^2.0.0
  geolocator: ^8.2.0
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.5
  google_maps_webservice: ^0.0.19
  google_sign_in: ^5.1.0
  http: ^0.13.5
  http_parser: ^4.0.2
  image_picker: ^0.8.4+8
  intl: ^0.18.0
  just_the_tooltip: ^0.0.12
  marquee: ^2.2.1
  path: ^1.8.2
  path_provider: ^2.0.1
  percent_indicator: ^4.2.3
  permission_handler: ^10.0.0
  phone_number: ^0.12.0+1
  photo_view: ^0.14.0
  pin_code_fields: ^7.0.0
  provider: ^6.0.3
  share: ^2.0.1
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0-nullsafety.0
  sign_in_with_apple: ^5.0.0
  sizer: ^2.0.15
  substring_highlight: ^1.0.33
  url_launcher: ^6.0.2
  video_player: any
  webview_flutter: ^3.0.0
  curved_navigation_bar: ^1.0.3
  flutter_spinkit: ^5.2.0
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/
    - assets/video/intro.mp4
    - assets/video/introdark.mp4

  fonts:
    - family: SF-Pro-Rounded-Regular
      fonts:
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 600
